packages:
  - 'fdm-core'
  - 'fdm-data'
  - 'fdm-calculator'
  - 'fdm-docs'
  - 'fdm-app'

catalog:
  better-auth: ^1.2.7
  drizzle-orm: ^0.41.0
  drizzle-kit: ^0.30.6
  "@dotenvx/dotenvx": ^1.39.0
  typescript: ^5.8.2
  vite: ^6.2.6
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.1
  "@vitest/coverage-v8": 3.1.1
  