packages:
  - 'fdm-core'
  - 'fdm-data'
  # - 'fdm-calculator'
  - 'fdm-docs'
  - 'fdm-app'

catalog:
  drizzle-orm: ^0.38.3
  drizzle-kit: ^0.30.1
  vite: ^6.0.7
  vite-tsconfig-paths: ^4.3.2
  vite-plugin-dts: ^4.4.0
  vite-dts: ^4.4.0
  vitest: ^2.1.8