packages:
  - 'fdm-core'
  - 'fdm-data'
  - 'fdm-calculator'
  - 'fdm-docs'
  - 'fdm-app'

catalog:
  better-auth: ^1.2.8
  drizzle-orm: ^0.43.1
  drizzle-kit: ^0.31.1
  "@dotenvx/dotenvx": ^1.44.1
  typescript: ^5.8.3
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.4
  "@vitest/coverage-v8": 3.1.4
  