packages:
  - 'fdm-core'
  - 'fdm-data'
  # - 'fdm-calculator'
  - 'fdm-docs'
  - 'fdm-app'

catalog:
  drizzle-orm: ^0.38.4
  drizzle-kit: ^0.30.2
  "@dotenvx/dotenvx": ^1.33.0
  typescript: ^5.7.3
  vite: ^6.0.11
  vite-tsconfig-paths: ^4.3.2
  vitest: ^2.1.8
  