packages:
  - 'fdm-core'
  - 'fdm-data'
  - 'fdm-calculator'
  - 'fdm-docs'
  - 'fdm-app'

catalog:
  better-auth: ^1.2.3
  drizzle-orm: ^0.40.0
  drizzle-kit: ^0.30.5
  "@dotenvx/dotenvx": ^1.38.5
  typescript: ^5.8.2
  vite: ^6.1.1
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.8
  "@vitest/coverage-v8": 3.0.8
  