packages:
  - fdm-core
  - fdm-data
  - fdm-calculator
  - fdm-docs
  - fdm-app

catalog:
  '@dotenvx/dotenvx': ^1.51.0
  '@rollup/plugin-commonjs': ^28.0.6
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.3
  '@rollup/plugin-terser': ^0.4.4
  '@rollup/plugin-typescript': ^12.1.4
  '@vitest/coverage-v8': 3.2.4
  better-auth: ^1.3.27
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  rollup: ^4.52.4
  rollup-plugin-polyfill-node: ^0.13.0
  typedoc: ^0.28.14
  typedoc-plugin-missing-exports: ^4.1.2
  typescript: ^5.9.3
  vite: ^7.1.10
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
