packages:
  - 'fdm-core'
  - 'fdm-data'
  - 'fdm-calculator'
  - 'fdm-docs'
  - 'fdm-app'

catalog:
  drizzle-orm: ^0.39.3
  drizzle-kit: ^0.30.4
  "@dotenvx/dotenvx": ^1.37.0
  typescript: ^5.7.3
  vite: ^6.0.11
  vite-tsconfig-paths: ^4.3.2
  vitest: ^3.0.6
  "@vitest/coverage-v8": 3.0.6
  