packages:
  - 'fdm-core'
  - 'fdm-data'
  - 'fdm-calculator'
  - 'fdm-docs'
  - 'fdm-app'

catalog:
  better-auth: ^1.2.8
  drizzle-orm: ^0.43.1
  drizzle-kit: ^0.31.1
  "@dotenvx/dotenvx": ^1.44.1
  typescript: ^5.8.3
  typedoc: "^0.28.5"
  typedoc-plugin-missing-exports: "^4.0.0"
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.4
  "@vitest/coverage-v8": 3.1.4
  rollup: ^4.41.1
  "rollup-plugin-polyfill-node": "^0.13.0"
  "@rollup/plugin-commonjs": "^28.0.3"
  "@rollup/plugin-json": "^6.1.0"
  "@rollup/plugin-node-resolve": "^16.0.1"
  "@rollup/plugin-terser": "^0.4.4"
  "@rollup/plugin-typescript": "^12.1.2"
