packages:
  - 'fdm-core'
  - 'fdm-data'
  - 'fdm-calculator'
  - 'fdm-docs'
  - 'fdm-app'

catalog:
  better-auth: ^1.2.7
  drizzle-orm: ^0.42.0
  drizzle-kit: ^0.31.0
  "@dotenvx/dotenvx": ^1.41.0
  typescript: ^5.8.3
  vite: ^6.3.2
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.2
  "@vitest/coverage-v8": 3.1.2
  